### ISSUE TITLE
Pathology data: log of why "This phenotype cannot be measured in this mouse model" is being shown

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/magora#100]
I'm not sure but I think this message can be shown for two reasons:
1. if there is null data (ie specimen is in the data but null value)
2. if the data exists for the model but no data exists for the control (ie specimens not in the data).

Is this true?

If so, can you provide a summary of which groups are missing from the data and which just have null values?

ie: in this screenshot, C57BL6/J is shown as "This phenotype cannot be measured in this mouse model" for Insoluble Abeta42 in the hippocampus. Were C57BL6/J specimens not present in the data? Or were they there but just blank/null/0 value?
<img width="1013" alt="Screen Shot 2022-05-11 at 10 19 11 AM" src="https://user-images.githubusercontent.com/40642407/167909068-f9000f66-f754-4f65-bd04-77cab07de96f.png">

Similarly, with hippocampus Dystrophic Neurites. One control (C57BL6/J) is labeled "This phenotype cannot be measured in this mouse model", but B6129 looks to have 0 values. Were C57BL6/J specimens not present in the data but B6129 were and were zero?

<img width="1046" alt="Screen Shot 2022-05-11 at 10 22 15 AM" src="https://user-images.githubusercontent.com/40642407/167909821-b60439de-369c-47bf-b61e-fb5c273d603a.png">

**Comment by sharlagelfand** [comment]
Need to distinguish between data cannot be measured, NA values, "legitimate" zeros. Will summarize the different cases of what's there/what's not and we'll come up with language around that.

**Comment by sharlagelfand** [comment]
@annagree Here's a summary of selections (phenotype/tissue) combinations that would currently cause *at least one* of the panels to have the "This phenotype cannot be measured in this mouse model" message (combinations that would have no panels with this message are not listed)

I've summarized the data for each model into 4 groups:
* **All NA**: Specimens appear in the data, but all values are NA
* **All 0**: Specimens appear in the data, but all values are 0
* **No data**: No specimens in the data for this model at all
* **Not all NA/0**: Specimens appear in the data, and not *all* are NA or 0 values - but some may be

Only the **All NA** and **No data** categorizations would cause a panel to have that (same message).

|phenotype                   |tissue          |C57BL/6J |5xFAD        |B6129        |3xTg-AD      |
|:---------------------------|:---------------|:--------|:------------|:------------|:------------|
|Dystrophic Neurites (LAMP1) |Cerebral Cortex |All NA   |Not all NA/0 |Not all NA/0 |Not all NA/0 |
|Dystrophic Neurites (LAMP1) |Hippocampus     |All NA   |Not all NA/0 |All 0        |Not all NA/0 |
|Insoluble Abeta40           |Cerebral Cortex |No data  |Not all NA/0 |No data      |Not all NA/0 |
|Insoluble Abeta40           |Hippocampus     |No data  |Not all NA/0 |No data      |Not all NA/0 |
|Insoluble Abeta42           |Cerebral Cortex |No data  |Not all NA/0 |No data      |Not all NA/0 |
|Insoluble Abeta42           |Hippocampus     |No data  |Not all NA/0 |No data      |Not all NA/0 |
|phospho-tau (AT8)           |Hippocampus     |No data  |No data      |All 0        |Not all NA/0 |
|Plaque Density (Thio-S)     |Cerebral Cortex |All NA   |Not all NA/0 |All 0        |All 0        |
|Plaque Density (Thio-S)     |Hippocampus     |All NA   |Not all NA/0 |All 0        |Not all NA/0 |
|Plaque Size (Thio-S)        |Cerebral Cortex |All NA   |Not all NA/0 |All 0        |All 0        |
|Plaque Size (Thio-S)        |Hippocampus     |All NA   |Not all NA/0 |All 0        |Not all NA/0 |
|Soluble Abeta40             |Cerebral Cortex |No data  |Not all NA/0 |No data      |Not all NA/0 |
|Soluble Abeta40             |Hippocampus     |No data  |Not all NA/0 |No data      |Not all NA/0 |
|Soluble Abeta42             |Cerebral Cortex |No data  |Not all NA/0 |No data      |Not all NA/0 |
|Soluble Abeta42             |Hippocampus     |No data  |Not all NA/0 |No data      |Not all NA/0 |
|Tau (HT7)                   |Hippocampus     |No data  |No data      |Not all NA/0 |Not all NA/0 |

So for example, for Dystrophic Neurites (LAMP1) with Cerebral Cortex tissue, the C57BL/6J panel has the message. FOr Tau (HT7) with Hippocampus tissue, both C57BL/6J and 5xFAD have this message.

Let me know if there's additional questions about this or if I can clarify anything! Thanks!
