### ISSUE TITLE
pathology data- incorporate data from new model (TREM2_R47H_NSS)

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/magora#103]
There is a new model that we'd like to incorporate into the Pathology explorer. This model is TREM2_R47H_NSS.

The data sources and metadata identifiers can be found in the [TREM2-NSS tab in this spreadsheet](https://docs.google.com/spreadsheets/d/1B3ZMReC7nR2CGgpFNJuxJTj__lF2h6dt/edit#gid=2134039283). 

This model is the first that will follow a new format, in which there are 4 associated groups that should be all shown in plots together (this is 4 instead of the 2 we have linked at this time). Going forward, most UCI models will follow this pattern. 

These are:
1. [MODEL]+5xFAD
2. [MODEL] alone
3. 5xFAD alone
4. C57BL6J control 

Would it be fairly straightforward to show all 4 plots linked together? I suspect these would look best in a 2x2 grid, rather than in a single row. 

We will also need to update the "Available Models and Data" tab. Is there an easy way for me to share that content?

**Comment by sharlagelfand** [comment]
Doesn't look like I have access to these files! @annagree @ryaxley is one of you able to give me access? Thanks!

**Comment by annagree** [comment]
@sharlagelfand can you remind me what your synapse username is?

**Comment by sharlagelfand** [comment]
@annagree yes! just "sharlagelfand"

**Comment by annagree** [comment]
The content for adding this model to the Available Models and Data table can be found in [this Google sheet](https://docs.google.com/spreadsheets/d/1KUctWyWRp0OXugmPeTUjzhRY0NvJf8QUKmrpyXmI54A/edit#gid=0).

**Comment by annagree** [comment]
@sharlagelfand A couple of additional updates on this one:
1. I noted one mistake in the units that I had originally sent. Plasma NFL should be `pg/ml` instead of pg/mg.
2. In addition, the Plasma NFL is actually not from cortex or hippocampus, but is from `plasma`. Does `plasma` already show up as a "tissue" in the biospecimen metadata? 

cc @ryaxley maybe you can help with the second question as well

**Comment by sharlagelfand** [comment]
Closed by #109.
