### ISSUE TITLE
Inconsistent units in pathology

### ISSUE THREAD

**Issue by sharlagelfand** [Sage-Bionetworks/magora#107]
@annagree Just noticed there are a few places where units are inconsistent in the pathology spreadsheet: https://docs.google.com/spreadsheets/d/1B3ZMReC7nR2CGgpFNJuxJTj__lF2h6dt/edit#gid=1924150660

For Dystrophic Neurites (LAMP1), 5xFAD units are `%` but for 3xTg-AD units are `total object volume (cubic mm)`
For Plaque Size (Thio-S), 5xFAD units are `mean object area (sqmm)`, but for 3xTg-AD units are `mean object volume (cubic mm)`

Assuming they should be consistent across models, so we likely want to update this. Thanks!

**Comment by annagree** [comment]
@sharlagelfand It turns out they updated their quantification strategy, so these different units across models are accurate.
