### ISSUE TITLE
Pathology data: update logic and message content for handling missing data

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/magora#108]
After conversations with the data contributors, we would like to update the way we are handling missing or null data.

We would like to introduce some special logic to some of the 5xFAD data, because it was originally entered in an incorrect way. This will be a one time exception for this model only.

For the all NA case, where specimens appear in the data, but all values are NA
- These specimens WERE measured and were found to be ZERO but they were entered as NA/blank.
- These values should be converted to ZERO and displayed as ZERO on the plot

For the No Data where no specimens in the data for this model at all
- These specimens WERE NOT measured  and so we should display a blank plot with a message.
- We want to update the message to say "Data Not Available"

Going forward, we won't have a situation like the "all NA case", so this is a historical exception.

**Comment by sharlagelfand** [comment]
@annagree to confirm, should we update the message from "This phenotype cannot be measured in this mouse model" to "Data Not Available" throughout?

**Comment by sharlagelfand** [comment]
Closed by #109.

**Comment by annagree** [comment]
cc @j-hendrickson-sage This ticket details some background on the null vs zero vs missing value issue I brought up.

**Comment by j-hendrickson-sage** [comment]
thanks @annagree
