### ISSUE TITLE
error in labels on ABCA7 model

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/magora#116]
It looks like there might have been a drag and fill error in Excel that I missed in the first round-- some of the labels are in/soluble Ab41 and Ab43. These should just be 40 or 42. I've updated [the sheet](https://docs.google.com/spreadsheets/d/1B3ZMReC7nR2CGgpFNJuxJTj__lF2h6dt/edit#gid=1274984612) to indicate the updates that are needed, but it should be as below:

<google-sheets-html-origin><style type="text/css"></style>

Display Name | Field Name 
-- | --
Soluble Abeta40 | Abeta40
Soluble Abeta40 | Abeta40
Soluble Abeta42 | Abeta42
Soluble Abeta42 | Abeta42
Insoluble Abeta40 | Abeta40
Insoluble Abeta40 | Abeta40
Insoluble Abeta42 | Abeta42
Insoluble Abeta42 | Abeta42

**Comment by sharlagelfand** [comment]
Closed by #118.
