### ISSUE TITLE
funny axes for some of the plots

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/magora#117]
The axes for some of the values where the data points are all zero look kind of funny because it seems like it's trying to autoscale to see the data but the values are all zero so it is super zoomed in. Is there a way to constrain this, or at least have the axis start at zero?
<img width="912" alt="Screen Shot 2022-06-07 at 4 49 41 PM" src="https://user-images.githubusercontent.com/40642407/172503150-848e8bee-be27-4952-9e94-0ab08544fd05.png">

**Comment by sharlagelfand** [comment]
We can definitely have it start from zero @annagree! We'll need to pick an upper bound for the plots in this case though - is there a number you have in mind (e.g. it would go from 0 to 1, 0 to 10, etc)?

**Comment by sharlagelfand** [comment]
Here's how these panels will look now:

<img width="886" alt="Screen Shot 2022-06-23 at 10 47 21 AM" src="https://user-images.githubusercontent.com/15895337/175327810-cc3bd4b7-1870-425a-b1db-37c79c54326a.png">

**Comment by sharlagelfand** [comment]
Closed by #128.
