### ISSUE TITLE
add in homepage content

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/magora#26]
Since there is space in the new designs some homepage content, I've come up with some draft content in this Google slide deck (slide #2). It doesn't exactly map 1:1 to the existing template, so let me know if you have any questions about layout. I wasn't sure what parts of the template were fixed and what could be easily modified. 
https://docs.google.com/presentation/d/1B66aAhB7mRgq14PbAiImTXG40H_D6y8xrirwUmCZkPw/edit#slide=id.gac08579ab5_0_73

**Comment by sharlagelfand** [comment]
Thanks @annagree! We can easily modify most of the template, no restrictions to follow the layout I initially gave. Here's an update of how that looks with the new content:

<img width="1436" alt="Screen Shot 2020-11-18 at 10 53 45 AM" src="https://user-images.githubusercontent.com/15895337/99553931-b09a6200-298c-11eb-8033-83000a7becea.png">
<img width="1436" alt="Screen Shot 2020-11-18 at 10 53 54 AM" src="https://user-images.githubusercontent.com/15895337/99553955-b3955280-298c-11eb-86fc-8631e42f30dc.png">
