### ISSUE TITLE
update strain labels using logic 

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/magora#44]
First need to update metadata as outlined here:

_For example for ABCA7KI:
Genotype: APOE4_HOMOZYGOUS; TREM2R47H_HOMOZYGOUS; ABCA7KI_HOMOZYGOUS
Would have modelSystemName= Abca7A1527GAPOE4Trem2R47H
modelCommonName= LOAD1.ABCA7KI
Genotype: APOE4_HOMOZYGOUS; TREM2R47H_HOMOZYGOUS; ABCA7KI_NONCARRIER
Would have modelSystemName= Abca7A1527GAPOE4Trem2R47H
BUT modelCommonName= LOAD1_

Adrian is planning to update the commonNames accordingly in this primary screen individual metadata file: https://www.synapse.org/#!Synapse:syn22107818

**Comment by annagree** [comment]
'individualCommonGenotype'

**Comment by sharlagelfand** [comment]
@annagree Here's details of the issue I mentioned with the pathology metadata:

The previous derivation was:

> if genotype ends with "_hemizygous", then it's the genotype with "_hemizygous" removed
> If genotype ends with "_noncarrier", then it's just genotype_background
> So the values are this (and mouse_line is what's used in the app)
> 
> ```
> genotype          genotype_background mouse_line
> 5XFAD_noncarrier  C57BL6J             C57BL6J  
> 5XFAD_hemizygous  C57BL6J             5XFAD  
> ```

Almost everything from the new individualCommonGenotype field matches this logic, but there are 3 with genotype = "5XFAD_noncarrier", genotypeBackground = "C57BL6J", and indivudualCommonGenotype = "5XFAD" - from the logic above it should be "C57BL6J":

```
  genotype         genotypeBackground mouse_line individualCommonGenotype     n
1 5XFAD_hemizygous C57BL6J            5XFAD      5XFAD                      143
2 5XFAD_noncarrier C57BL6J            C57BL6J    5XFAD                        3
3 5XFAD_noncarrier C57BL6J            C57BL6J    C57BL6J                    150
```

Here are the individuals with mismatches: 330, 792, 1586
