### ISSUE TITLE
nanostring data: exclude groups with less than 3 subjects

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/magora#45]
There are a few misc heterozygotes (ie CECAM1_HETEROZYGOUS) that snuck through the screen. We’ll leave them in place in the data and metadata but will need to update the code to exclude any group that has less than 3 individuals from the analysis.

**Comment by sharlagelfand** [comment]
@annagree I think I remember you saying that these got removed from the data, is that correct?

Looks like none of the models have < 3 subjects, so I'm inclined to think yes (and no removal needs to be done on my end even if not!):

```
   mouse_model         n_specimens
 1 5XFAD                        18
 2 LOAD1.Clasp2L163P            24
 3 LOAD1.Snx1D465N              24
 4 APOE4                        31
 5 C57BL6J                      32
 6 LOAD1.CEACAM1KO              32
 7 LOAD1.CR1long                34
 8 LOAD1.Il1rapExon2KO          35
 9 Trem2R47H                    35
10 LOAD1.ABCA7A1527G            36
11 LOAD1.MthfrC677T             45
12 LOAD1                       101
```

**Comment by annagree** [comment]
@sharlagelfand yep you're right! This is no longer needed.
