### ISSUE TITLE
update to "age" grouping across the app

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/magora#46]
We are currently using death-birth to calculate age, but this is not always accurate of the cohort/age group.

The teams are going to update the metadata to add the "age cohort" as a new column... this is still in progress.

**Comment by annagree** [comment]
The metadata is in the process of being updated-- should happen in the next day or so!
It will now include new "ageDeath" and "ageDeathUnit" columns.

**Comment by annagree** [comment]
The pathology metadata for 5xFAD (syn18880070) has been updated. 
The nanostring metadata (syn22107818) has also been updated!

**Comment by sharlagelfand** [comment]
Just took a look at the pathology metadata, there is one individual whose age is 181 instead of 18 - I think just a typo!

```
  individualID jobNumber         ageDeath
           566 [5xfAD] 18 Months      181
```

**Comment by sharlagelfand** [comment]
@annagree Re: the nanostring metadata, ages mainly look good! Just a couple to flag / get on your radar.

The ages are mainly 4 - 12 months, but one is 14 (in our original range / on the legend, so may be fine) and one is 23 months:

```
    age     n
1     4   219
2     6     6
3     8   167
4    12   338
5    14     1
6    23     1
```

Here are the two "outliers":

```
  individual_id sex      age mouse_model
1         33675 Female    23 LOAD1      
2         20887 Female    14 Trem2R47H  
```

Thanks!

**Comment by annagree** [comment]
@sharlagelfand I checked with the teams and have corrected the two values and reuploaded a new version (24 and 12 months, respectively). On another note, when looking back at the metadata file I realized there are some individuals in there that we should exclude from the nanostring analysis. Anyone who has a value in 'treatmentType' should be excluded. We should only include mice where **'treatmentType' is null**.




<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:////Users/agreenwood/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel="File-List" href="file:////Users/agreenwood/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>





treatmentType
--

**Comment by sharlagelfand** [comment]
@annagree Thanks for updating! I'll update the analysis only to include those with null `treatmentType`.

**Comment by sharlagelfand** [comment]
These updates seem done and closed as part of #73!

To note, there are some inconsistencies with ages in the gene expressions data (not with metadata, but ages are contained in the files themselves):

The data sets in https://www.synapse.org/#!Synapse:syn25312847 are 2 and 22mon, while the rest of the data sets fall within 4, 8, 12, 18, and 24 (as expected / consistent with the rest of the app).

**Comment by sharlagelfand** [comment]
@annagree I was looking at the nanostring data to update the age groups (e.g. just to use actual ages in the plot) and noticed there are some individuals with age 6 months in the [metadata](https://www.synapse.org/#!Synapse:syn22107818) (that are also in the actual nanostring data):

```
  individual_id
          <dbl>
1         46863
2         46871
3         46874
4         46875
5         46886
6         46889
```

There is also one that is age 24 months, but it's not in the nanostring data so might not need to worry about it. Here is the ID just in case : `33675`

I think we were expecting 4, 8, 12 months only. Should these 6 months ones be excluded? Thanks!

**Comment by sharlagelfand** [comment]
Hmmm, nevermind @annagree! There are no age 6 controls so they drop off from the analysis anyways - just 4, 8, and 12 left. Sorry for the false alarm!

**Comment by annagree** [comment]
ok great! Thanks @sharlagelfand
