### ISSUE TITLE
no visible binding for global variable ‘phenotypes’

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/magora#6]
R CMD check doesn't like that we are using phenotypes data even though it is part of the package and definitely available. I think prefixing `phenotypes` with `magora::` in `expand_mouse_line_factor` and `mod_pathology_ui`/`mod_pathology_server` should placate it.

**Comment by sharlagelfand** [comment]
I was so surprised that it needs to be namespaced! Will be fixed in #4

**Comment by karawoo** [comment]
I agree it's super weird!
