### ISSUE TITLE
Error when phenotype/tissue combo has no data

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/magora#8]
With the old excel file we chose not to display phenotypes that didn't have any data. Now the situation is a little more complex as some combinations of phenotype and tissue don't have data, and cause an error:
<img width="875" alt="Screen Shot 2020-06-25 at 11 46 50 AM" src="https://user-images.githubusercontent.com/4452678/85781092-2e0dbf00-b6da-11ea-9f10-3e684e4094df.png">

<img width="892" alt="Screen Shot 2020-06-25 at 11 46 41 AM" src="https://user-images.githubusercontent.com/4452678/85781086-2cdc9200-b6da-11ea-9828-7321106b549a.png">

I guess it makes sense that "Plasma AB 42" is only relevant for plasma samples, not brain tissue. I can think of a couple options here: 1 is to try to display a custom message instead e.g. "No data exists for the selected combination of phenotype, model, and tissue", another would be to use shiny's `updatePickerInput` to constrain what tissue options are available.

**Comment by sharlagelfand** [comment]
I think it makes sense to update the tissue options with `updatePickerInput` - I wonder if later on with more mouse lines we'll run into the case where some phenotype/mouse line combinations aren't available too. I'll keep an eye on the data as it updates and see.
