### ISSUE TITLE
Pathology data: scale plots by phenotype AND model

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/magora#98]
Is it possible to update the logic in how axes are scaled, such that each model-CTRL combo can be scaled separately?
For example, in this screenshot, 5xFAD has much smaller values than 3xTg, and it would be nice to see these expanded. 
<img width="1024" alt="Screen Shot 2022-05-11 at 10 08 52 AM" src="https://user-images.githubusercontent.com/40642407/167907581-b0ed3e2d-a070-42ed-ab84-7efb3b534198.png">

**Comment by sharlagelfand** [comment]
Need to distinguish between data cannot be measured, NA values, "legitimate" zeros. Will summarize the different cases of what's there/what's not and we'll come up with language around that.

**Comment by j-hendrickson-sage** [comment]
Good!
